/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import {useStore} from '../App'
import * as THREE from 'three'

function damp(target, to, step, delta, v = new THREE.Vector3()) {
  if (target instanceof THREE.Vector3) {
    target.x =  THREE.MathUtils.damp(target.x, to[0], step, delta)
    target.y =  THREE.MathUtils.damp(target.y, to[1], step, delta)
    target.z =  THREE.MathUtils.damp(target.z, to[2], step, delta)
  }
}
function lerp(target, to, step, delta, v = new THREE.Vector3()) {
  if (target instanceof THREE.Vector3) {
    target.x =  THREE.MathUtils.lerp(target.x, to[0], step, delta)
    target.y =  THREE.MathUtils.lerp(target.y, to[1], step, delta)
    target.z =  THREE.MathUtils.lerp(target.z, to[2], step, delta)
  }
}



export default function Model({ ...props }) {
  const group = useRef()
  
  const { nodes, materials,  } = useGLTF('/6Uedit.gltf')
 // const { materials: solar } = useGLTF('/solar.gltf')
  
  const {focus, animating, mainVisible} = useStore(state => state);
  const step = 4
  const animPrecision = 0.01
  
  const mainCamPos = [ 0.6306514463594766,  -0.4210648696664135,  0.712496367900918]
  const thrusterCamPos = [0.15798008711065167, 0.07600188037031083, 0.14511212262143952]
  const lensCamPos = [0.12753831577671065, -0.10407153882968664, -0.16412881074068325]
  const antCamPos = [0.07344901323458229,  0.39355321519639064,  -0.12187571040583152]
  
  //const mainCamRot = [0.8517,  0, 0.56009]
  const thrusterCamRot = [ 0.10307643035331633,  0.8681327726105077, -0.07877646275676702]
  const lensCamRot = [2.5764873027205804, 0.5807592536680115,  -2.8067933644197485]
  const antCamRot = [-1.9535678507085672,  0.4007292400075513,  2.3720121819878806]
  

  const thrusterQuat = [0.9062088093489014, 0.030162790074321634, 0.42151981664988497, -0.014030114925622953]

  const satMat = nodes.CubePanel_8037_Mesh004.material


  useFrame( (state, delta) => {
    if(focus === 'init'){
      if(animating){
      state.camera.fov = THREE.MathUtils.damp(state.camera.fov,  50, step, delta)
      damp(state.camera.position, mainCamPos, step, delta)
      state.camera.lookAt(0, 0.2, 0)
      //state.camera.updateProjectionMatrix()

      if(Math.abs(state.camera.position.x - mainCamPos[0]) < animPrecision){
        useStore.setState(
          { 
            animating: false, 
            rotate: true,
            mainVisible: true,
          });
        }
      }

      state.camera.lookAt(0, 0.2, 0)

    }  else if(focus === 'lens'){ 
    if(animating){
  state.camera.fov = THREE.MathUtils.damp(state.camera.fov,  50, step, 0.001)
  damp(state.camera.position, lensCamPos, step, delta)
  //damp(state.camera.rotation, lensCamRot, step, delta)
  state.camera.lookAt(0, 0, 0)
  
  //state.camera.updateProjectionMatrix()
  if(Math.abs(state.camera.position.x - lensCamPos[0]) < animPrecision){
    useStore.setState({ animating: false, rotate: true,
    });
  }

  state.camera.lookAt(0, 0, 0)
  }

  //state.camera.lookAt(0,-0.5, 0)
 //state.camera.lookAt(0, 0, 0)
  
}else if(focus === 'thruster'){ 
  if(animating){
state.camera.fov = THREE.MathUtils.damp(state.camera.fov,  50, 8, 0.05)
damp(state.camera.position, thrusterCamPos, step, delta)
damp(state.camera.rotation, thrusterCamRot, step, delta)
state.camera.lookAt(0, 0.2, 0)

state.camera.updateProjectionMatrix()
if(Math.abs(state.camera.position.x - thrusterCamPos[0]) < animPrecision){
  useStore.setState({ animating: false, rotate: true,
  });
}
}

//state.camera.lookAt(0, 0, 0)
state.camera.lookAt(0, 0.17, 0)

}/* else if(focus === 'antenna'){ 
  if(animating){
state.camera.fov = THREE.MathUtils.damp(state.camera.fov,  50, step, delta)
damp(state.camera.position, antCamPos, step, delta)
damp(state.camera.rotation, antCamRot, step, delta)
state.camera.lookAt(0, 0, 0)

state.camera.updateProjectionMatrix()
if(Math.abs(state.camera.position.x - lensCamPos[0]) < animPrecision){
  useStore.setState({ animating: false, rotate: true,
  });
}
}

//state.camera.lookAt(0,-0.5, 0)
//state.camera.lookAt(0, 0, 0)

} */

  }
  
  
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Anetanna_1002_Mesh004.geometry}
        material={nodes.Anetanna_1002_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Anetanna_1003_Mesh004.geometry}
        material={nodes.Anetanna_1003_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Box019001_Mesh014.geometry}
        material={nodes.Box019001_Mesh014.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Box019001_Mesh015.geometry}
        material={nodes.Box019001_Mesh015.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Box019001_Mesh016.geometry}
        material={nodes.Box019001_Mesh016.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Box019001_Mesh017.geometry}
        material={nodes.Box019001_Mesh017.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.CubePanel_8015_Mesh010.geometry}
        material={nodes.CubePanel_8015_Mesh010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8015_Mesh011.geometry}
        material={nodes.CubePanel_8015_Mesh011.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8015_Mesh012.geometry}
        material={nodes.CubePanel_8015_Mesh012.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8025_Mesh004.geometry}
        material={nodes.CubePanel_8025_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8026_Mesh004.geometry}
        material={nodes.CubePanel_8026_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8037_Mesh004.geometry}
        material={nodes.CubePanel_8037_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8040_Mesh004.geometry}
        material={nodes.CubePanel_8040_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8041_Mesh004.geometry}
        material={nodes.CubePanel_8041_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8042_Mesh004.geometry}
        material={nodes.CubePanel_8042_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8044_Mesh004.geometry}
        material={nodes.CubePanel_8044_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8045_Mesh004.geometry}
        material={nodes.CubePanel_8045_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_8046_Mesh004.geometry}
        material={nodes.CubePanel_8046_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_014001_Mesh005.geometry}
        material={nodes.CubePanel_014001_Mesh005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_014002_Mesh005.geometry}
        material={nodes.CubePanel_014002_Mesh005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_014003_Mesh005.geometry}
        material={nodes.CubePanel_014003_Mesh005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_014004_Mesh005.geometry}
        material={nodes.CubePanel_014004_Mesh005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_014005_Mesh004.geometry}
        material={nodes.CubePanel_014005_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_014007_Mesh004.geometry}
        material={nodes.CubePanel_014007_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.CubePanel_014008_Mesh004.geometry}
        material={nodes.CubePanel_014008_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.IridiumAntenna_1001_Mesh004.geometry}
        material={materials['steel_backplate.003']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.IridiumAntenna_2001_Mesh004.geometry}
        material={materials['steel_backplate.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Main_Lens_Cylinder008.geometry}
        material={nodes.Main_Lens_Cylinder008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Main_Lens_Cylinder009.geometry}
        material={nodes.Main_Lens_Cylinder009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Motor_Rod_1001_Mesh004.geometry}
        material={materials['None.004']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Phased_Array_Antenna_2001_Mesh002_Phased_Array_Antenna_2001_.geometry}
        material={materials['logoST.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Phased_Array_Antenna_2001_Mesh005.geometry}
        //material={nodes.Phased_Array_Antenna_2001_Mesh005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh129_SolarPanel_043001_Mesh192.geometry}
        material={nodes.SolarPanel_043001_Mesh129_SolarPanel_043001_Mesh192.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh193.geometry}
        material={nodes.SolarPanel_043001_Mesh193.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh194.geometry}
        material={nodes.SolarPanel_043001_Mesh194.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh195.geometry}
        material={nodes.SolarPanel_043001_Mesh195.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh196.geometry}
        material={nodes.SolarPanel_043001_Mesh196.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh197.geometry}
        material={nodes.SolarPanel_043001_Mesh197.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh198.geometry}
        material={nodes.SolarPanel_043001_Mesh198.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh199.geometry}
        material={nodes.SolarPanel_043001_Mesh199.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh200.geometry}
        material={nodes.SolarPanel_043001_Mesh200.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh201.geometry}
        material={nodes.SolarPanel_043001_Mesh201.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh202.geometry}
        material={nodes.SolarPanel_043001_Mesh202.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh203.geometry}
        material={nodes.SolarPanel_043001_Mesh203.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh204.geometry}
        material={nodes.SolarPanel_043001_Mesh204.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh205.geometry}
        material={nodes.SolarPanel_043001_Mesh205.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh206.geometry}
        material={nodes.SolarPanel_043001_Mesh206.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh207.geometry}
        material={nodes.SolarPanel_043001_Mesh207.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh208.geometry}
        material={nodes.SolarPanel_043001_Mesh208.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh209.geometry}
        material={nodes.SolarPanel_043001_Mesh209.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh210.geometry}
        material={nodes.SolarPanel_043001_Mesh210.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh211.geometry}
        material={nodes.SolarPanel_043001_Mesh211.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh212.geometry}
        material={nodes.SolarPanel_043001_Mesh212.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh213.geometry}
        material={nodes.SolarPanel_043001_Mesh213.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh214.geometry}
        material={nodes.SolarPanel_043001_Mesh214.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh215.geometry}
        material={nodes.SolarPanel_043001_Mesh215.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh216.geometry}
        material={nodes.SolarPanel_043001_Mesh216.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh217.geometry}
        material={nodes.SolarPanel_043001_Mesh217.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh218.geometry}
        material={nodes.SolarPanel_043001_Mesh218.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh219.geometry}
        material={nodes.SolarPanel_043001_Mesh219.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh220.geometry}
        material={nodes.SolarPanel_043001_Mesh220.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh221.geometry}
        material={nodes.SolarPanel_043001_Mesh221.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh222.geometry}
        material={nodes.SolarPanel_043001_Mesh222.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh223.geometry}
        material={nodes.SolarPanel_043001_Mesh223.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh224.geometry}
        material={nodes.SolarPanel_043001_Mesh224.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh225.geometry}
        material={nodes.SolarPanel_043001_Mesh225.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh226.geometry}
        material={nodes.SolarPanel_043001_Mesh226.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh227.geometry}
        material={nodes.SolarPanel_043001_Mesh227.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh228.geometry}
        material={nodes.SolarPanel_043001_Mesh228.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh229.geometry}
        material={nodes.SolarPanel_043001_Mesh229.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh230.geometry}
        material={nodes.SolarPanel_043001_Mesh230.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh231.geometry}
        material={nodes.SolarPanel_043001_Mesh231.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh232.geometry}
        material={nodes.SolarPanel_043001_Mesh232.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh233.geometry}
        material={nodes.SolarPanel_043001_Mesh233.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh234.geometry}
        material={nodes.SolarPanel_043001_Mesh234.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh235.geometry}
        material={nodes.SolarPanel_043001_Mesh235.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh236.geometry}
        material={nodes.SolarPanel_043001_Mesh236.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh237.geometry}
        material={nodes.SolarPanel_043001_Mesh237.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh238.geometry}
        material={nodes.SolarPanel_043001_Mesh238.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh239.geometry}
        material={nodes.SolarPanel_043001_Mesh239.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh240.geometry}
        material={nodes.SolarPanel_043001_Mesh240.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh241.geometry}
        material={nodes.SolarPanel_043001_Mesh241.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh242.geometry}
        material={nodes.SolarPanel_043001_Mesh242.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh243.geometry}
        material={nodes.SolarPanel_043001_Mesh243.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh244.geometry}
        material={nodes.SolarPanel_043001_Mesh244.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh245.geometry}
        material={nodes.SolarPanel_043001_Mesh245.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh066_SolarPanel_044001_Mesh001.geometry}
        material={nodes.SolarPanel_044001_Mesh066_SolarPanel_044001_Mesh001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh129_SolarPanel_044001_Mesh192.geometry}
        material={nodes.SolarPanel_044001_Mesh129_SolarPanel_044001_Mesh192.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh193.geometry}
        material={nodes.SolarPanel_044001_Mesh193.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh194.geometry}
        material={nodes.SolarPanel_044001_Mesh194.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh195.geometry}
        material={nodes.SolarPanel_044001_Mesh195.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh196.geometry}
        material={nodes.SolarPanel_044001_Mesh196.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh197.geometry}
        material={nodes.SolarPanel_044001_Mesh197.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh198.geometry}
        material={nodes.SolarPanel_044001_Mesh198.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh199.geometry}
        material={nodes.SolarPanel_044001_Mesh199.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh200.geometry}
        material={nodes.SolarPanel_044001_Mesh200.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh201.geometry}
        material={nodes.SolarPanel_044001_Mesh201.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh202.geometry}
        material={nodes.SolarPanel_044001_Mesh202.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh203.geometry}
        material={nodes.SolarPanel_044001_Mesh203.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh204.geometry}
        material={nodes.SolarPanel_044001_Mesh204.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh205.geometry}
        material={nodes.SolarPanel_044001_Mesh205.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh206.geometry}
        material={nodes.SolarPanel_044001_Mesh206.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh207.geometry}
        material={nodes.SolarPanel_044001_Mesh207.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh208.geometry}
        material={nodes.SolarPanel_044001_Mesh208.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh209.geometry}
        material={nodes.SolarPanel_044001_Mesh209.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh210.geometry}
        material={nodes.SolarPanel_044001_Mesh210.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh211.geometry}
        material={nodes.SolarPanel_044001_Mesh211.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh212.geometry}
        material={nodes.SolarPanel_044001_Mesh212.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh213.geometry}
        material={nodes.SolarPanel_044001_Mesh213.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh214.geometry}
        material={nodes.SolarPanel_044001_Mesh214.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh215.geometry}
        material={nodes.SolarPanel_044001_Mesh215.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh216.geometry}
        material={nodes.SolarPanel_044001_Mesh216.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh217.geometry}
        material={nodes.SolarPanel_044001_Mesh217.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh218.geometry}
        material={nodes.SolarPanel_044001_Mesh218.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh219.geometry}
        material={nodes.SolarPanel_044001_Mesh219.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh221.geometry}
        material={nodes.SolarPanel_044001_Mesh221.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh222.geometry}
        material={nodes.SolarPanel_044001_Mesh222.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh223.geometry}
        material={nodes.SolarPanel_044001_Mesh223.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh224.geometry}
        material={nodes.SolarPanel_044001_Mesh224.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh225.geometry}
        material={nodes.SolarPanel_044001_Mesh225.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh226.geometry}
        material={nodes.SolarPanel_044001_Mesh226.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh227.geometry}
        material={nodes.SolarPanel_044001_Mesh227.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh228.geometry}
        material={nodes.SolarPanel_044001_Mesh228.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh229.geometry}
        material={nodes.SolarPanel_044001_Mesh229.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh230.geometry}
        material={nodes.SolarPanel_044001_Mesh230.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh231.geometry}
        material={nodes.SolarPanel_044001_Mesh231.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh232.geometry}
        material={nodes.SolarPanel_044001_Mesh232.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh233.geometry}
        material={nodes.SolarPanel_044001_Mesh233.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh234.geometry}
        material={nodes.SolarPanel_044001_Mesh234.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh235.geometry}
        material={nodes.SolarPanel_044001_Mesh235.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh236.geometry}
        material={nodes.SolarPanel_044001_Mesh236.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh237.geometry}
        material={nodes.SolarPanel_044001_Mesh237.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh238.geometry}
        material={nodes.SolarPanel_044001_Mesh238.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh239.geometry}
        material={nodes.SolarPanel_044001_Mesh239.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh240.geometry}
        material={nodes.SolarPanel_044001_Mesh240.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh241.geometry}
        material={nodes.SolarPanel_044001_Mesh241.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh242.geometry}
        material={nodes.SolarPanel_044001_Mesh242.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh243.geometry}
        material={nodes.SolarPanel_044001_Mesh243.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_044001_Mesh244.geometry}
        material={nodes.SolarPanel_044001_Mesh244.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.TrueLens008.geometry}
        material={nodes.TrueLens008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.TrueLens009.geometry}
        material={nodes.TrueLens009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Box005001_Mesh004.geometry}
        material={materials.Old_White_Metal_NONE}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Electronics_Box001_Mesh004.geometry}
        material={nodes.Electronics_Box001_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Power_Module_Box001_Mesh004.geometry}
        material={nodes.Power_Module_Box001_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Rotation_Arm001_Mesh004.geometry}
        material={nodes.Rotation_Arm001_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Thruster001_Mesh004.geometry}
        material={nodes.Thruster001_Mesh004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.SolarPanel_043001_Mesh001.geometry}
        material={nodes.SolarPanel_043001_Mesh001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
    
  )
}

useGLTF.preload('/6Uedit.gltf')
